import compose3d.Mesh
import compose3d.parseObj
import compose3d.resources.Res
import org.jetbrains.compose.resources.ExperimentalResourceApi

/**
 * Loads the teapot mesh from `teapot.obj`, bundled as a Compose Multiplatform
 * resource (`common/src/commonMain/composeResources/files/teapot.obj`) so
 * every target shares one copy and one loader, instead of desktop reading it
 * off its own classpath. `Res` is generated by the Compose resources Gradle
 * plugin into the package set by `compose.resources.packageOfResClass` in
 * common/build.gradle.kts.
 */
@OptIn(ExperimentalResourceApi::class)
suspend fun loadTeapotMesh(): Mesh {
    val bytes = Res.readBytes("files/teapot.obj")
    return parseObj(bytes.decodeToString(), "teapot")
}
